### PR TITLE
Fixed issue with handling link taps in empty space after the link

### PR DESCRIPTION
**Pull request by lukagabric**
As I mentioned in [this issue](https://github.com/optonaut/ActiveLabel.swift/issues/239), in current active label example you have a shortened link at the and of the text. The issue is that you can tap in the empty space after the link and touches will be accepted. The issue is even more apparent when you have just one or two words in that final line and touches are accepted through out that line in an empty space. This PR fixes the issue and allows touches only on the link.

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
Hi @lukagabric,
Any idea why this only happens to .url and not .hashtag selector?

Thanks

**Comment by lukagabric** [comment]
Hey @maziyarpanahi, sorry for the late reply, but I did not test with .hashtag so I'm not sure what is going on there. I just fixed this for the purposes of my project.

**Comment by anand79indugapalli** [comment]
i used your code in my pod and whitespace after the pod was not clicking but now before white space is clicking, let me know if you have any solution for it.

thanks in advacne

**Comment by lukagabric** [comment]
@anand79indugapalli, sorry but I'm not working on this, I just fixed what I needed for my project and created a PR in case this is of interest to the project...

**Pull request closed without merging**
