### PR TITLE
[Added] Font and Underline style on active type

### PR DESCRIPTION
**Pull request by cikpis**

### CODE REVIEW

**Comment by cikpis** [comment]
This also include https://github.com/optonaut/ActiveLabel.swift/pull/193/commits/9ac014fd863946572c34abbd30d9a91d4feaacca commit

**Comment by cikpis** [comment]
@poolqf Hey man! could you accept please this PR? It's requested from a lot of users and it would be a wonderful feature to have :)

Thanks a lot in advance!

**Comment by cikpis** [comment]
@poolqf hey man, any news about this?

**Comment by maziyarpanahi** [comment]
Hi @cikpis, This is pull request has some conflicts and some changes that I am not really sure. I will ask other contributors to take a look at it. Many thnkgs

**Comment by cikpis** [comment]
After 7 months it’s possible that it has some conflict. If I have time I’ll update the PR.

**Comment by limsangjin12** [comment]
👍

**Pull request closed without merging**
