### PR TITLE
Add under line options

### PR DESCRIPTION
**Pull request by yutmr**
Add under line options to all ActiveTypes.(related to #104)
And changed ActiveElement's range to trimmed range.
Because regular expression result often contains white space.
It is not pretty.
**before**
screen shot 2017-01-21 at 4 36 21
**after**
screen shot 2017-01-21 at 4 45 00

### CODE REVIEW

**Comment by stalexxx** [comment]
great!

**Comment by milesalex** [comment]
Will this be merged? Need this!!!

**Comment by viktorwillmann** [comment]
merge pls

**Comment by lmcd** [comment]
Can we get this merged?

**Comment by CoolHandLuke88** [comment]
Any update on when this can be merged?

**Comment by maziyarpanahi** [comment]
I know it's a bit late, but if you guys can resolve the conflict I can give a try to merge.

**Comment by adamirowe** [comment]
Did this get merged?

**Pull request closed without merging**
