### PR TITLE
Update project to Swift 4.2

### PR DESCRIPTION
**Pull request by BalestraPatrick**
You should probably create a separate `swift-4.2` branch since it's still in beta for now, but it's good to merge this in the main repo to avoid every client to use their own updated fork.

### CODE REVIEW

**Comment by anthonygeranio** [comment]
Yes! Need this.

**Comment by maziyarpanahi** [comment]
Thanks @BalestraPatrick,

I will do some tests and change Travis config to see how this pans out once they release the latest version after 12th of September. Just to be sure what to expect.
Having another branch is a good idea to make sure people still can access 4.0 for the time being.

**Comment by anthonygeranio** [comment]
@maziyarpanahi In the mean time how can I utilize this in my project + cocoapods which is upgraded to Swift 4.2? cc: @BalestraPatrick

**Comment by anthonygeranio** [comment]
Follow up!

You can add something like this to your Podfile

```
pod 'ActiveLabel', :git => 'https://github.com/BalestraPatrick/ActiveLabel.swift/', :branch => 'feature/swift-4.2'
```

**Comment by anthonygeranio** [comment]
I guess we also need this to be updated to 4.1 too...

**Comment by maziyarpanahi** [comment]
My entire app is 4.2 except this lib. There is no problem to have your codes and other pods in 4.2 and have some pods compile with 4.0

**Comment by maziyarpanahi** [comment]
Here is the release: https://github.com/optonaut/ActiveLabel.swift/releases/tag/1.0.1

**Pull request closed without merging**
