### PR TITLE
Add support for other languages

### PR DESCRIPTION
**Pull request by alexbat98**

### CODE REVIEW

**Comment by schickling** [comment]
Thank you @alexbat98!

@Hua-san, @weifans, @Estanque could you please verify if this works for you as well?

**Comment by hdogan** [comment]
I've tested and it works as expected.

**Comment by hdogan** [comment]
Related issues are #18 and #2

**Comment by nanhuo** [comment]
Still not working with Chinese. In Chinese, whitespace is NOT required in front of  '@' and '＃' . So splitting string into words by `_textString.componentsSeparatedByCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet())`  does not work.

**Pull request closed without merging**
