### PR TITLE
Adjust height to zero when there's no text set

### LINKED ISSUE #106: Auto layout height problem.
http://stackoverflow.com/questions/39106506/set-the-kilabel-or-activelabels-height-to-0-when-it-has-no-string-but-original

Here is my issue.

String empty but ActiveLabel's height still one line's height.

UILabel is working fine.

Anyone know about this issue?

### PR DESCRIPTION
**Pull request by filipealva**
Implement @cruisediary suggestion to fix #106

### CODE REVIEW

**Comment by filipealva** [comment]
@optonaut someone could please merge it so I can stop using a modified version of the pod? thanks <3

**Comment by maziyarpanahi** [comment]
Yes, I need to merge some PRs and release a new version compatible with new XCode/Swift

**Comment by maziyarpanahi** [comment]
@filipealva Could you please resolve the conflict to be included in the next release?

**Comment by filipealva** [comment]
@maziyarpanahi done

**Pull request merged**
