### PR TITLE
Change URL recognition to NSDataDetector, add capabilities to recognize phone numbers, change regex for mentions, hashtags and URLs and add active elements manually

### PR DESCRIPTION
**Pull request by dsinkovskiy**
Change URL recognition to NSDataDetector, add capabilities to recognize phone numbers, change regex for mentions, hashtags and URLs and add active elements manually

### CODE REVIEW

**Comment by dsinkovskiy** [comment]
Added capability to change regex

**Comment by poolqf** [comment]
Please split this PR in multiple ones. There are some interesting things and others that have to be rethought

**Comment by dsinkovskiy** [comment]
@poolqf , there are already some separate commits for each feature:
1. URL recognition change to NSDataDetector
2. Add capability to use other regex for mentions, hashtags and url recognition
3. Add addActiveElement feature
4. Add phone numbers recognition
I've tried to save the code style for the new code.

Which features do you want me to exclude?

**Comment by poolqf** [comment]
Hi @dsinkovskiy , 
First of all, sorry I sounded rude before, was not the intention

1. We've run away from NSDataDetector because is 2x slower than regex.
2. The default regex should not be optionals, but be defaulted to the RegexParser values. Also, I don't understand this change: `hashtag.range.length > 1`
3. I prefer the approach that @devmario did in #72, your approach is not as readable
4. As I said for `1.`, NSDataDetector is slow and we should avoid it

That's the reason why it would be better to split all the points in separate PRs 😄

**Comment by poolqf** [comment]
With today's merge, this PR is now not mergeable anymore. The new implementation is allowing adding new default types of highlighting patterns easily. You should not have any problem to adapt this PR to be merged.

**Pull request closed without merging**
