### PR TITLE
Element calculation

### PR DESCRIPTION
**Pull request by Enter91**
I found out that tapping anywhere outside text activates link, hashtag or mention that is closest to glyph for CGPoint location. I've added a while-loop that calculates bounding rects line by line to avoid using bounding rect for whole text therefore it's possible to avoid clicks on shorter lines of text. Additionally I've added checks to stop counting rects if minY exceeds touch point.

Screenshot below shows current implementation:
simulator screen shot - iphone x - 2018-10-02 at 23 06 52

Here's fixed rects calculation:
simulator screen shot - iphone x - 2018-10-02 at 23 04 31

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
I would like to take a look at this and fix this empty space in front of the URL issue.
Thanks @Enter91

**Comment by maziyarpanahi** [comment]
This will be added to the next release with Swift 5.0 support.

**Comment by maziyarpanahi** [comment]
@Enter91 
Is it possible to merge with the new master and resolve the conflicts? I like to merge this in the next release (1.1.5) next week,
Many thanks

**Comment by Enter91** [comment]
@maziyarpanahi Done :)

**Comment by maziyarpanahi** [comment]
Perfect! Thank you.

**Pull request closed without merging**
