### PR TITLE
Fixed typo maxLenght

### PR DESCRIPTION
**Pull request by iSapozhnik**

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
Hi @iSapozhnik,
Thanks for your contribution, if I understand correctly these changes are entirely internal and it won't change the way users asking for those functions right?

**Comment by iSapozhnik** [comment]
Hey @maziyarpanahi,
Yep, should be fine.

**Comment by maziyarpanahi** [comment]
awesome! If the changes are done I can merge your pull request.

**Comment by iSapozhnik** [comment]
I think I'm done :)

**Comment by maziyarpanahi** [comment]
Great, thanks again for your contribution.

**Pull request merged**
