### PR TITLE
Improve table view performance

### LINKED ISSUE #9: Usernames with periods are not fully highlighted
Would it be possible to expand the search for usernames to include ones that have periods in them, such as my name "@alex.figueroa"? It is currently being highlighted only until the period. (It seems Github does this with their markdown too 😅)

activelabelscreenshot

### PR DESCRIPTION
**Pull request by poolqf**
#### :tophat: What? Why?
As pointed out in #27 , when using ActiveLabel inside a cell, the whole customisation process that is behind any change on it, makes the table to drop a lot of frames.
The customisation ActiveLabel is doing on every change is expensive, so the intention is to try to reduce the cost of every change.

### Things covered:

- **Changed towards a tableView Demo**
This change may not be the better option as a the example project, so considering changing it back to the current example.. 🤔

    - [x] Revert to previous Example

- **Rethought way to extract elements from the label text:**
Previously the way ActiveLabel was searching for `ActiveElement`s was by iterating through all the words the label had, and then passing a Regex individually to each one of them to see if they were `ActiveElement`s or not.
Now the Regex Parser is passing the Regex to the whole text at once. And extracting elements based in specific Regex for each `ActiveType`

    - [x] Added `RegexParser` whose only responsibility is to manage Regex related things
    - [x] Added `ActiveBuilder`. Taking advantage of the RegexParser creates `ActiveElement`s
    - [x] Removed top level functions that were passing a regex to each work

- **Changed Way to Test**
Previously, the way ActiveElement was checking things was by checking if an String was satisfying the requirements to be an specific ActiveType. This way of testing has been broken with the refactor, so the new way the tests are working now is by passing a text to an `ActiveLabel` and expect that it to contain X amount of active elements, and check the string and type of it.

    - [x] Change Tests
    - [x] Add more Tests

- **Perform only necessary things when changing variables**
At the moment, each time the user sets a property (overridden & custom) we are executing `updateTextStorage()`. This is expensive, and could be a bottleneck.

    - [x] Avoid calling `updateTextStorage()` if possible when changing a prop

- **Regex is now detecting `#` and `@` in the middle of words**
That should not occur :no_entry: 

    - [x] Avoid detecting `#` and `@` in the middle of words ( Closes #9  )

- Move `urlDetector` to use regex:
I've been looking for a correct URL Regex, and I've came across with this page: https://mathiasbynens.be/demo/url-regex. The option I've chosen is the one purposed by @krijnhoetmer, and I've tweaked it a bit

    - [x] Use regex for the `urlDetector`

    :warning: Dropped support for detecting urls like `google.com`.
    Maintaining support for old school `www.google.com`

#### 📈 DATA

This table reflects the necessary time to customise a cell changing text and textAlignment when calling `cellForRow`:

| Necessary time (s)  | Before  | After  |
|:-:|:-:|---|
| First iteration  | 0.015 - 0.020  |  0.002 - 0.003  |
| Going **async**  | 0.015 - 0.020  |  0.0005 - 0.0007  |

**In some cases 10x less time :scream:**

#### :open_mouth: IMPORTANT:
Even that this PR reduces the label reuse cost, it is not completely solving the issue

### CODE REVIEW

**Comment by poolqf** [comment]
@schickling Any ideas on how to reduce more the reuse time?

**Comment by poolqf** [comment]
After profiling a little bit more, here we have 2 really expensive lines:

- `return urlDetector.matchesInString(text, options: [], range: range)` - RegexParser.swift - line 28
- `textStorage.setAttributedString(mutAttrString)` - ActiveLabel.swift - line 189

Seems like NSDataDetector is slower than a custom Regex... Maybe we should move to a regex for the URLs?

**Comment by schickling** [comment]
@poolqf unfortunately I'm very short on time at the moment but moving to Regex sounds good to me!

**Comment by poolqf** [comment]
@schickling 
**Quick update:**

:warning: Dropped support for detecting urls like google.com.
Maintaining support for old school www.google.com
(Same as what github does)

There is no good REGEX way to achieve google.com detection  as far as I know (and tried)

I think this PR **should not be merged** until you have time to completely review it.
I'll use all this changes in my app, to test if it is breaking changes :wink:

**Comment by poolqf** [comment]
Two issues found now:

- urls like pic.twitter.com/XXXX are not highlighted :no_entry: 
- going async means you cannot dynamically calculate the cell height on the cellForRow :-1:

**Comment by poolqf** [comment]
pic.twitter urls fixed. Ready to review @schickling :wink:

**Comment by poolqf** [comment]
**Quick update**

Been using this refactor in my personal app, and I did not have any issues related to it :tada:

**Comment by schickling** [comment]
LGTM :+1:

**Comment by JaviSoto** [comment]
Hey!

I just updated to the latest Pod version which includes this, and I'm getting a consistent crash here:

```swift
mutAttrString.setAttributes(attributes, range: element.range)
```

Which is called asynchronously from `updateTextStorage`. That `dispatch_async` seems like asking for trouble (race conditions). In fact, if I remove the `dispatch_async` and call the method synchronously, the crash doesn't happen.

I was just wondering if you've seen anything like this. Would you like me to create an issue? I tried to look for the root cause but I can't seem to find exactly why this is happening.
This is the exception being thrown:

```
2016-02-04 11:16:44.206 [78159:5339064] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111d45e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001117bedeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111d45d9d +[NSException raise:format:] + 205
	3   Foundation                          0x000000011139a5ee -[NSMutableRLEArray replaceObjectsInRange:withObject:length:] + 146
	4   Foundation                          0x00000001113b7bfb -[NSConcreteMutableAttributedString setAttributes:range:] + 95
	5   ActiveLabel                         0x000000010f2c450f _TFC11ActiveLabel11ActiveLabelP33_42C3D6786121DF647E596543A9DC427916addLinkAttributefS0_FCSo25NSMutableAttributedStringT_ + 2911
	6   ActiveLabel                         0x000000010f2cac31 _TFFC11ActiveLabel11ActiveLabelP33_42C3D6786121DF647E596543A9DC427917updateTextStorageFS0_FT9parseTextSb_T_U_FT_T_ + 49
```

**Comment by poolqf** [comment]
Hi @JaviSoto ,

Seems related with #14 . I've been using the 0.4.0 version in a personal app, without issues. But @byAmmerix complained about it few days ago. It is possibly related with the `dispatch_async`.

I'll try to look at it, but let's follow this up in #14. Would you mind to give there a little bit of info about the environment you are using (sdk, ios version..)?

Thanks!

**Pull request merged**
