### PR TITLE
'characters' Deprecation

### PR DESCRIPTION
**Pull request by xuaninbox**
Fix 'characters' is deprecated: Please use String or Substring directly

### CODE REVIEW

**Comment by iSapozhnik** [comment]
Any chances to have this PR merged ?

**Comment by maziyarpanahi** [comment]
I can look into it

**Comment by iSapozhnik** [comment]
@maziyarpanahi would be really nice. It's basically suppressing warning by using `word.count`, that's it.

**Comment by SeRG1k17** [comment]
@maziyarpanahi Please, merge it.

**Pull request merged**
